### PR TITLE
Add MaxChordSize modifier

### PR DESCRIPTION
**Pull request by Illirick**

### CODE REVIEW

**Comment by semyon422** [comment]
Thanks for PR.
1) the order of inputs `self.noteChart:getInputIterator()` is not defined. This can lead to the fact that notes will be deleted differently on different plays.
2) Notes are deleted based on the order of `self.noteChart:getInputIterator()`. This leads to imbalance of notes. For example, if you set the value to 1, then one column will be heavily overloaded.

The best implementation should take note balance into account and save jacks and trills.
I can accept this this PR as is but I will not guarantee replay backward compatibility for this mod.

**Comment by Illirick** [comment]
Would it be better to use `getLayerDataIterator()` here instead?

**Comment by semyon422** [comment]
i would do it like this:
- compute time difference between notes on each column
- insert all ShortNotes in a new array of chords: `{{n1, n2}, {n3}, {n1, n4}}`
- sorted all notes in chords by their column ascending
- removed notes on chords that larger than modifier value. Such notes, that have lowest (or highest) time difference to the next note, one by one. If notes have same dt, remove the most left of them.

This should work well

**Comment by semyon422** [comment]
Implemented by me.

**Pull request closed without merging**
